#!/usr/bin/env python3
"""Reproduce all paper figures from pre-computed results.

Figure 1: Periodogram panels (4 domains)
Figure 2: Z24 Bridge damage tracking
Figure 3: CV gradient with bootstrap CIs (from bootstrap_ci_analysis.py)

Usage:
    python analysis/generate_figures.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
FIG_DIR = ROOT / "paper" / "figures"
FIG_DATA = FIG_DIR / "data"


def figure1_periodogram_panels() -> None:
    """Figure 1: Lomb-Scargle periodogram panels across domains."""
    panels = {
        "a": ("Bearing (BPFO)", "panel_a_bearing.json"),
        "c": ("Structural (LUMO)", "panel_c_structural.json"),
        "d": ("Volcanic (Kīlauea)", "panel_d_volcanic.json"),
        "e": ("HRV (VLF)", "panel_e_hrv.json"),
    }

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes = axes.flatten()

    for idx, (label, (title, fname)) in enumerate(panels.items()):
        path = FIG_DATA / fname
        if not path.exists():
            print(f"  [skip] {fname} not found")
            axes[idx].set_visible(False)
            continue

        with open(path) as f:
            data = json.load(f)

        freqs = np.array(data["frequencies"])
        powers = np.array(data["powers"])
        peak_freq = data.get("peak_frequency")

        ax = axes[idx]
        ax.plot(freqs, powers, "k-", linewidth=0.5, alpha=0.8)
        if peak_freq is not None:
            ax.axvline(peak_freq, color="red", linestyle="--", alpha=0.7,
                       label=f"Peak: {peak_freq:.4f}")
            ax.legend(fontsize=8)
        ax.set_title(f"({label}) {title}", fontsize=11)
        ax.set_xlabel("Frequency")
        ax.set_ylabel("Power")

    fig.tight_layout()
    out = FIG_DIR / "fig1_periodogram_panel_reproduced.pdf"
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out}")


def figure2_z24_tracking() -> None:
    """Figure 2: Z24 Bridge frequency tracking and damage detection."""
    csv_path = ROOT / "shm" / "z24" / "results" / "z24_damage_predictions.csv"
    if not csv_path.exists():
        print("  [skip] z24_damage_predictions.csv not found")
        return

    df = pd.read_csv(csv_path)

    fig, ax = plt.subplots(figsize=(12, 5))

    if "measurement_index" in df.columns and "frequency" in df.columns:
        x = df["measurement_index"]
        y = df["frequency"]
        ax.plot(x, y, "b-", linewidth=0.8, label="1st natural frequency")

        if "damage_label" in df.columns:
            damage = df[df["damage_label"] == 1]
            if len(damage) > 0:
                ax.axvspan(damage["measurement_index"].min(),
                           damage["measurement_index"].max(),
                           alpha=0.15, color="red", label="Damage period")

        ax.set_xlabel("Measurement Index")
        ax.set_ylabel("Frequency (Hz)")
        ax.set_title("Z24 Bridge — First Natural Frequency Tracking")
        ax.legend()

    fig.tight_layout()
    out = FIG_DIR / "fig2_z24_tracking_reproduced.pdf"
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out}")


def figure3_cv_gradient() -> None:
    """Figure 3: CV gradient — delegates to bootstrap_ci_analysis.py."""
    print("  Figure 3 is generated by: python analysis/bootstrap_ci_analysis.py")
    print("  (contains full bootstrap CI computation + CV gradient plot)")


def main() -> None:
    print("Generating paper figures...\n")

    print("Figure 1: Periodogram panels")
    figure1_periodogram_panels()

    print("\nFigure 2: Z24 damage tracking")
    figure2_z24_tracking()

    print("\nFigure 3: CV gradient with bootstrap CIs")
    figure3_cv_gradient()

    print("\nDone.")


if __name__ == "__main__":
    main()
